ALTER TABLE public.perfumes
  ADD COLUMN IF NOT EXISTS perfil_olfativo TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS notas_saida TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS notas_coracao TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS notas_fundo TEXT NOT NULL DEFAULT '';